# Generated by Django 5.0.4 on 2024-04-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, editable=False, verbose_name='event time')),
                ('remote_ip', models.GenericIPAddressField(db_index=True, editable=False, verbose_name='source ip address')),
                ('method', models.CharField(editable=False, max_length=10, verbose_name='http method')),
                ('uri', models.URLField(db_index=True, editable=False, verbose_name='requested uri')),
                ('response_status_code', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(599)], verbose_name='response status code')),
                ('response_size', models.PositiveIntegerField(editable=False, verbose_name='response size')),
            ],
            options={
                'verbose_name': 'Parsed nginx log',
                'verbose_name_plural': 'Parsed nginx logs',
            },
        ),
    ]
